### ISSUE TITLE
Expected non-null value, resolve delegate return null for \"$SitecoreQL.Types.IdGraphType\""

### ISSUE THREAD

**Issue by GoranHalvarsson** [kmazzoni/SitecoreQL#1]
Hey
Great stuff :-)
Unfortunately, I get the following error:
Expected non-null value, resolve delegate return null for \"$SitecoreQL.Types.IdGraphType\""

In class SitecoreQL.Query.ItemQuery, if I comment out Field:
this.Field<SearchQueryType>("search",
                "Search against all Sitecore items by providing various filter/sort/faceting options.", ....

 Then it works fine, but that means I cant use the "search". 

Any idea what it can be?

**Comment by kmazzoni** [comment]
Hey @GoranHalvarsson,

I'm having trouble reproducing the issue.  Based on the error it seems the NRE is occurring when trying to resolve the item's ID.  Is it possible to try rebuilding the `sitecore_web_index` index?  I also pushed a couple of changes to try and better handle NRE's for the item ID.

If that doesn't work can you try a search query that does not include the `id` and see if that returns anything?  Something like:

```
{
  search(first: 5) {
    totalCount
    items {
      name
      language
      databaseName
    }
  }
}
```
Also, let me know what version and update of Sitecore you are working with.  I'm currently testing against Sitecore 8.2 (rev. 170728).

Thanks.

**Comment by GoranHalvarsson** [comment]
Thanks,

I still have this issue though :(
Im testing aginst sitecore 9.01

**Comment by GoranHalvarsson** [comment]
The issue seems to be the search field in itemquery. I cant run anything, I just get the error:
Expected non-null value, resolve delegate return null for "$SitecoreQL.Types.IdGraphType"

If I comment out the entire search field in ItemQuery:
Field("search",
"Search against all Sitecore items by providing various filter/sort/faceting options.", ....

Then xpath and item will work.

So it has something todo with the Field("search", ...
